version: '3.5'
services:
  transformer_proxy:
    container_name: phoros-transformer-proxy
    build: server/
    image: omarzos/transformer-proxy
    volumes:
      - ./server:/code
    hostname: phoros-transformer-proxy
    command: uvicorn --host phoros-transformer-proxy server:app --reload
    ports:
      - 9976:8000
    env_file:
      - env/rabbitmq_listen.env
      - env/rabbitmq_publish.env
      - env/storage.env
    networks:
      - phoros_net
networks:
  phoros_net:
    external:  true      
      
